### ISSUE TITLE
Observations on `Periodic Signal Intuition.ipynb`

### ISSUE THREAD

**Issue by sayakpaul** [ariG23498/DigitalSignalProcessing#1]
Good introduction and conveyance of your intuition @ariG23498. However, if you want this to be spread and specifically want this to be more of a reference point (where people will keep coming back to this notebook), consider briefly penning down the major concepts involved here. For example, start the notebook by defining the **motto** of coding everything down and plotting interesting graphs here, what is a **time-period** and so on. 

The following portion is completely spot on. However, consider elaborating on the `constructive` and `destructive` interference parts if possible. 

> Both the signals are periodic, and they have a common multiple too 
This multiple is the point where they both repeat themselves 
When the amplitudes of the two signals will be superimposed on themselves, the common multiple point is where the new signal will repeat itself, the other points can have `constructive` interference of `destructive` interference and hence their individual periodic points are of least interest.

Now coming to the conclusion you have given - 
> This is the sole reason as to why we find out the least common multiple of the two periodic signals and try to obtain the period of the new signal.

Has this something to do with finding the most dominant portions of a signal (I am finding relevance to the initial parts of doing FFT here)? Feel free to bump me if I am wrong here.

**Comment by ariG23498** [comment]
Thank you for your valuable feedback @sayakpaul . I will definitely look in to the `constructive` and `destructive` interference portions, and am soon going to come up with a valid introduction to start the notebook. I am not sure about the later portion of your issue, this notebook is just an intuition of the periodicity of two periodic wave forms, it does not talk about the initial parts of doing FFT. As suggested by Ayush Thakur, i will quickly come up with another notebook that will only consist of the intuitions of Fourier Transforms.

**Comment by sayakpaul** [comment]
I meant to ask does obtaining the least common multiple of the two periodic signals have anything to do about the finding the most dominant portions of a signal?

**Comment by ariG23498** [comment]
@sayakpaul let us call this a point where both the signals start afresh simultaneously, cannot term it to be `dominant`.
