### ISSUE TITLE
Feedback on "Aliasing.ipynb"

### ISSUE THREAD

**Issue by sayakpaul** [ariG23498/DigitalSignalProcessing#2]
@ariG23498 here's what I think of the `Aliasing.ipynb` - 

- Nothing specified as to brief about what **aliasing** is.

- What is the motivation behind discretizing a continuous signal?  

  > Provided a continuous time fucntion, x(t) We can discretise the function by taking samples of the same function, x[n] = x(nT)
  
  Also, a little bit of explanation to break which symbol stands for what in the notations would have been great!

- Like I mentioned these following two plots are going to stay with me - 
![image](https://user-images.githubusercontent.com/22957388/56707069-12ed9b00-6735-11e9-9144-1b17adc8ebea.png)

- Consider the following code snippet - 

 ```python
    c[i] = np.sin(2*np.pi*0.1*i)
    c1[i] = np.sin(2*np.pi*0.1*i + 2*np.pi*1*fs*i)
    c2[i] = np.sin(2*np.pi*0.1*i + 2*np.pi*2*fs*i)
```
  No annotations provided here. Consider writing the equations in a separate cell before the code section. Also, consider labeling these plots to indicate which equation is governing which signal: 
![image](https://user-images.githubusercontent.com/22957388/56707038-edf92800-6734-11e9-87f2-52d6dcff5ff9.png)

- You have generated some amazing plots. But you have not mentioned what did you try to convey (brief summaries/titles that you see after figures in the books/articles).

-  > I wanted everyone to get confused at this instant.
Now the curtain raiser.
Nyquist says, whenever we take samples at a sampling rate of fs we alias all the continuous signals that have frequencies lesser than that of half of fs.

This is good but I think is a bit vague too. Before stating what Nyquist had proposed, it would have been better if you could elaborate what **alias** means here. 

- Referring to the following section - 
![image](https://user-images.githubusercontent.com/22957388/56707427-614f6980-6736-11e9-8351-4c55bbfb9388.png)
  
  **Reasons** of what? This is an example where you could have summarized the above plots and then come to this section. 

- Code comments above the major sections would have been great. 

- What is the following plot conveying? (Also, the axis labels are overlapping)
 
![image](https://user-images.githubusercontent.com/22957388/56707517-d622a380-6736-11e9-8753-af00dce89555.png)
 
This is all **I** personally felt. If anything is irrelevant here (sorry about that and pardon my unwisdom) let me know about it as well.

**Comment by ariG23498** [comment]
@sayakpaul nothing about the issue raised here is irrelevant, would come up with better explanations, and a proper definition as to what is happening. `Alaising` is a big topic, i will restructure my notebook in a jiffy.
